services:
  # client:
  #   container_name: client
  #   image: client:1.0.0
  #   restart: unless-stopped
  #   env_file: ./.env
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - api

  api:
    container_name: api
    image: api:1.0.0
    restart: unless-stopped
    env_file: ./.env
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongo
    volumes:
      - ./api:/api # For development only

  mongo:
    container_name: mongo
    image: mongo:6-jammy
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8081:8081
    depends_on:
      - mongo

volumes:
  db:
